services:
  - type: worker
    name: bbws-api
    region: singapore
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery --app tasks worker --loglevel info --concurrency 4"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: rekt-test
          type: redis
          property: connectionString
    fields:
      REDIS_IP: 'a'
      REDIS_PASS: 'a'
      START_CODE: 'a'
      DISCORD_CHANNEL: '{"BTC": 1064447410350329876, "ETH": 1064447463936765952, "SOL": 1064447463936765952}'
      DISCORD_TOKEN: 'a'
      DISCORD_USER: 0
      DISCORD_WEBHOOK: 'a'
      API_KEY: 'a'
      API_SECRET: 'a'

  - type: web
    name: flow
    region: singapore
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    plan: free
    # envVars:
    #   - key: CELERY_BROKER_URL
    #     fromService:
    #       name: rekt-redis
    #       type: redis
    #       property: connectionString
    fields:
      REDIS_IP: 'a'
      REDIS_PASS: 'a'
      START_CODE: 'a'
      SECRET_KEY: 'a'
      API_KEY: 'a'
      API_SECRET: 'a'
      RENDER_API: 'a'
      RENDER_SERVICE: 'a'
      AWS_ACCESS_KEY_ID: 'a'
      AWS_SECRET_ACCESS_KEY: 'a'
      LOGIN: '{"user": "", "code": ""}'

  - type: redis
    name: rekt-redis
    region: singapore
    plan: free # we choose a plan with persistence to ensure tasks are not lost upon restart
    maxmemoryPolicy: noeviction # recommended policy for queues
    ipAllowList: # required - allow external connections from everywhere
      - source: 0.0.0.0/0
        description: everywhere
