services:
  - type: worker
    name: bbws-api
    region: singapore
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery --app tasks worker --loglevel info --concurrency 4"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: rekt-test
          type: redis
          property: connectionString
  - type: web
    name: flow
    region: singapore
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    plan: free
    # envVars:
    #   - key: CELERY_BROKER_URL
    #     fromService:
    #       name: rekt-redis
    #       type: redis
    #       property: connectionString

  - type: redis
    name: rekt-redis
    region: singapore
    plan: free # we choose a plan with persistence to ensure tasks are not lost upon restart
    maxmemoryPolicy: noeviction # recommended policy for queues
    ipAllowList: # required - allow external connections from everywhere
      - source: 0.0.0.0/0
        description: everywhere
